### PR TITLE
Fix newapp() docstring

### LINKED ISSUE #518: An easy fix of Genie.newapp docstring
`Genie.newapp` has a docstring defined in `Genie.jl`, but it is kind of outdated. `Geine.Generator.newapp` has the updated (I believe) docstring. 
Simply delete the docstring in `Genie.jl` would fix this inconsistency.

### PR DESCRIPTION
**Pull request by chunjiw**
Fix #518

### CODE REVIEW

**Comment by AbhimanyuAryan** [comment]
removing the doc string will not fix the issue. Can you update the doc string and remove the inconsistencies? Not signature and doc string will make using `newapp` complicated for users

**Comment by chunjiw** [comment]
I think since we have `const newapp  = Generator.newapp`, the docstring of the former inherits that of the latter. This is true for `newapp_webservice` and other similar functions which have no docstring in Genie.jl.

If we keep the docstring only in Generator.jl, then it is easier to maintain. 

Let me know if I'm mistaken :)

**Comment by AbhimanyuAryan** [comment]
@essenciary can suggest better

**Comment by essenciary** [comment]
We're now working on Genie 5 (breaking release) where we're cleaning up a lot of the APIs - so I was actually thinking about removing all these aliases from `Genie` and keeping everything in `Genie.Generator`. Creating new apps is a rare task (it's by definition performed once per app/project) and makes no sense to pollute the Genie namespace. Thoughts?

**Comment by chunjiw** [comment]
That's good news! Looking forward to Genie 5!

**Comment by essenciary** [comment]
> That's good news! Looking forward to Genie 5!

It's gonna be awesome! 
Sneak peek: https://github.com/GenieFramework/Genie.jl/tree/v5

**Comment by chunjiw** [comment]
Closed this since it will be obsolete with the upcoming Genie 5

**Pull request closed without merging**
