### PR TITLE
Replace eval statements of SECRET_TOKEN with a global Ref approach

### PR DESCRIPTION
**Pull request by mirkobunse**
Until now, Genie uses a global constant `SECRET_TOKEN`, which is set through eval statements within other modules. Eval statements in other modules are bad style because they break the separation of concerns introduced by modules. Moreover, they break a potential pre-compilation of the code. On the journey to possibly get rid of all eval statements, I started by replacing those related to the `SECRET_TOKEN`.

The secret token is now stored inside a `Ref` object, instead of a constant. These objects are Julia's way of reserving a place for a global variable of which the value might change after pre-compilation. Since the token is read on startup, this concept perfectly fits the secret token. Since a `Ref` already defines the type of the value, it assists the compiler in optimizing code during pre-compilation.

The token is now set through accessor functions `Genie.secret_token!(token)` (setter) and `Genie.secret_token()` (getter). The getter also takes care of generating a temporary token if none is specified.

Will this PR break something? Feature-wise, no. However, I changed the syntax of the `config/secret_token.jl` file, so that users will need to re-generate this file with `Genie.Generator.write_secrets_file()`. To assist the user, an informative warning is emitted in this case, which explains what failed and what to do.

### CODE REVIEW

**Comment by mirkobunse** [comment]
Oh, I also fixed a bug in the Generator, which affects the unit tests: Until now, the `testmode=true` flag was not passed all the way down, so that it did not result in the Genie dependency being `dev`-ed. Actually, doing so is important for the test app that is generated during the unit tests. Otherwise, the test app would depend on the latest release of Genie, but not on the latest commit.

And yet another thing: I think this PR can serve as a blueprint for the other eval-statements which regard global constants, particularly `config` and `ASSET_FINGERPRINT`. These two have bothered me in #310 .

**Comment by essenciary** [comment]
@mirkobunse Thank you for this contribution, this is awesome! 

Can you please confirm that with this change, the `SECRET_TOKEN` is still persisted between app restarts?

**Comment by mirkobunse** [comment]
Sure, the token is persisted. The `config/secret.jl` file is included -- just like before -- and now reads as follows:

```julia
Genie.secret_token!("f280a5adf30d6f072c8b8b1cc4b4623f029ec4a20624142f3aba62531bf15aae") 
```

Regarding compatibility, however, the new syntax requires users to re-generate the `config/secret.jl` file, thus producing a different token. I can offer to implement a function `Generator.migrate_secrets_file` with which users can change the syntax of `config/secrets.jl` without changing the token itself.

**Comment by mirkobunse** [comment]
> Regarding compatibility, however, the new syntax requires users to re-generate the config/secret.jl file, thus producing a different token. I can offer to implement a function Generator.migrate_secrets_file with which users can change the syntax of config/secrets.jl without changing the token itself.

I implemented `Generator.migrate_secrets_file`. Moreover, the old syntax now will keep working as a fallback. A warning is issued, but nothing breaks.

**Comment by essenciary** [comment]
> I implemented `Generator.migrate_secrets_file`. Moreover, the old syntax now will keep working as a fallback. A warning is issued, but nothing breaks.

This is fantastic, works like a charm! Thanks so much! 🤩

**Comment by mirkobunse** [comment]
You're welcome! I'm glad you like it.

I plan to do similar replacements for `ASSET_FINGERPRINT` and `config` some time soon.

**Pull request merged**
