### PR TITLE
Form data with the same name overwrite each other

### PR DESCRIPTION
**Pull request by iskyd**
This refers to this issue: https://github.com/GenieFramework/Genie.jl/issues/456
It is a breaking change since HttpPostData data type changed from Dict{String,String} to Dict{String,Any}.

Let me know if this could be an acceptable solution and what needs to be done in order to have a good pull request.

### CODE REVIEW

**Comment by essenciary** [comment]
@iskyd What about making it `Dict{<:AbstractString,<:Any}` - that would be no breaking.

**Comment by iskyd** [comment]
@essenciary thanks for pointing this out. I'm not sure how to implement this since
`Dict{String,<:Any}()`

throw
MethodError: no method matching (Dict{String})()

**Comment by iskyd** [comment]
@essenciary I've also added a test case for this feature.

**Comment by tecosaur** [comment]
Why not be more specific and go with `Dict{<:AbstractString, <:Union{String, Vector{String}}}` ?

**Comment by iskyd** [comment]
Thanks @tecosaur. Sorry if I didn't came up with this in the first place but I think this is the best solution. I alredy did some changes in order to make this works. 
I just have one question @essenciary, I didn't notice that before but postpayload() (here : https://github.com/GenieFramework/Genie.jl/blob/master/src/Requests.jl#L111) always return Dict{Symbol,Any} so I don't think this is a breaking change. What do you think?

**Pull request merged**
