### PR TITLE
Use PrecompileSignatures.jl

### PR DESCRIPTION
**Pull request by rikhuijzer**
I wrote a package called [`PrecompileSignatures.jl`](https://github.com/rikhuijzer/PrecompileSignatures.jl) to speed up package loading time. When adding it to `Genie.jl`, it makes `precompile` take 16 seconds longer, makes `using Genie` take 1 second longer and reduces the time for the first running webserver by 1 second. I leave it up to you to decide whether this tradeoff is interesting/worth it. Note that I only benchmarked the code below, so there might be more effect for some other function calls.

## Benchmark

```julia
using Pkg
Pkg.precompile()

@time @eval using Genie
import Genie.Router: route
import Genie.Renderer.Json: json

using Genie.HTTP

# Warmup
HTTP.get("https://example.com")

@async begin
    Genie.config.run_as_server = true

    route("/") do
        (:message => "Hi there!") |> json
    end

    Genie.startup()
end

# Give the server some time to start.
sleep(1)

@time @eval HTTP.get("http://127.0.0.1:8000")
```

### Before this PR (`master`) - Julia 1.7.3

```
  1 dependency successfully precompiled in 8 seconds (55 already precompiled)
  3.150201 seconds (5.92 M allocations: 342.803 MiB, 6.34% gc time, 67.92% compilation time)
  7.201561 seconds (16.62 M allocations: 873.522 MiB, 4.33% gc time, 99.97% compilation time)
```

### This PR - Julia 1.7.3

```
1 dependency successfully precompiled in 25 seconds (55 already precompiled)
  4.375188 seconds (8.38 M allocations: 500.447 MiB, 6.07% gc time, 49.09% compilation time)
  6.329759 seconds (14.37 M allocations: 755.809 MiB, 3.84% gc time, 99.96% compilation time)
```

### CODE REVIEW

**Comment by rikhuijzer** [comment]
@essenciary I'll contact you on Slack/Zulip to schedule a meeting. I think that's the quickest way to answer your questions

**Comment by essenciary** [comment]
@rikhuijzer Currently trying this out, wondering if it has any effect.

image

**Comment by essenciary** [comment]
It doesn't seem to have the same effect as precompiling a custom image... how can we confirm that things get done? 

image

**Comment by essenciary** [comment]
Very interesting, with a precompiled image, RAM usage hover a bit over 500 MB. While with non-precompiled it's over 700 MB, flat.

**Comment by rikhuijzer** [comment]
> It doesn't seem to have the same effect as precompiling a custom image... how can we confirm that things get done?

That's correct. `PackageCompiler.jl` will have a greater effect. `PrecompileSignatures.jl` has less effects on reducing TTFX, but is easier to integrate in a package.

**Comment by essenciary** [comment]
> > It doesn't seem to have the same effect as precompiling a custom image... how can we confirm that things get done?
> 
> That's correct. `PackageCompiler.jl` will have a greater effect. `PrecompileSignatures.jl` has less effects on reducing TTFX, but is easier to integrate in a package.

Thanks Rik! Is there any way to check/measure if/how much was precompiled? It seems to go very fast over that block of code.

**Comment by rikhuijzer** [comment]
> Is there any way to check/measure if/how much was precompiled?

You can verify whether method `f` was precompiled by checking `methods(f)[1].specializations`. If it is precompiled, then there will be specializations. More generally, I'm just running benchmarks `@time @eval begin` to see the effects and don't know easier ways to check the effects.

**Comment by rikhuijzer** [comment]
I think I misunderstood your question. I've added the following to the [README.md](https://github.com/rikhuijzer/PrecompileSignatures.jl) which might answer your question:

> ## How can I see what signatures this package creates?
>
> Use
> ```julia
> PrecompileSignatures.precompilables(Foo)
> ```
> where `Foo` is the name of your package.
>
> ## How can I see whether the created signatures are valid?
>  
> By default, this package doesn't verify the `precompile` directives to avoid breaking precompilation in worst-case scenarios.
> To verify the directives for debugging purposes, use
> ```julia
> types = PrecompileSignatures.precompilables(Foo)
> @assert all(precompile.(types))
> ```
> where `Foo` is the name of your package.

**Pull request closed without merging**
