### PR TITLE
Tidyup patch

### PR DESCRIPTION
**Pull request by aminya**
Based on the results of the tests. Now, most of the tests pass nicely.

I dropped Julia 1.0 because MbelTLS 0.7 only supports Julia 1.2 and above. If you think MbelTLS compat can be relaxed (like using older versions), we can support Julia 1.0 again.

### CODE REVIEW

**Comment by aminya** [comment]
Windows tests fail. I think the error requires technical knowledge of Genie internals. 
Some temp files are missing:
https://github.com/GenieFramework/Genie.jl/pull/191/checks?check_run_id=379172404#step:5:50

**Comment by essenciary** [comment]
Same for Julia 1.0 - looks like a dependency issue. Maybe we should just remove tests for anything under 1.3? 

I'll dig into the windows issue.

**Comment by aminya** [comment]
> Same for Julia 1.0 - looks like a dependency issue. Maybe we should just remove tests for anything under 1.3?

Yes, tests are disabled. Now we only test on 1.3 and nightly. Although we support 1.2 too.

If you are determined to support Julia 1.0, you should edit the compat line for MbedTLS to this:
```yaml
MbedTLS = "0.6.7, 0.7"
```
This will relax its version requirement allowing to support Julia 1.0 again. You should test it yourself to check if it actually works though.

**Comment by aminya** [comment]
Also, I recommend removing `Manifest.toml` in the master to resolve the conflict. You shouldn't commit Manifest unless you want to add a specific **unregistered** package as your dependency (which you don't have any).

**Comment by essenciary** [comment]
@aminya Thanks for the tips! Sorry, I didn't notice you submitted a PR for the changes. I think not testing on Julia 1.0 is fine, I'm not committed to explicitly supporting it anyway. I'll merge. 

Re `Manifest.toml` I agree. I'll remove.

**Pull request merged**
