### PR TITLE
Unit testing of Genie apps

### LINKED ISSUE #281: Cannot test unnamed project
**Describe the bug**
On Gitter, I promised to report an issue that I had with Genie last week. I tried to set up testing, which failed, as can be seen below.

**Error stacktrace**
```
(MyApp) pkg> test
ERROR: trying to test unnamed project
```

**To reproduce**
```julia
julia> using Genie

julia> Genie.newapp_webservice("MyApp")
...

julia> exit()

$> cd MyApp/

$> mkdir test

$> echo -e "using Test \nusing MyApp \n\n@testset \"MyApp\" begin \n@test 1 == 1 \nend" > test/runtests.jl

$> julia

pkg> activate .

(MyApp) pkg> test
ERROR: trying to test unnamed project
```

**Expected behavior**
```
(MyApp) pkg> test
Test Summary: | Pass  Total
MyApp         |    1      1
```

**Additional context**
```julia
julia> versioninfo() 
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  ...

pkg> st
...
[c43c736e] Genie v1.1.0
...
[8dfed614] Test
```

### PR DESCRIPTION
**Pull request by mirkobunse**
This PR prepares the `Project.toml` of a new app for unit testing by adding a name and uuid. Further, it generates a `test/runtests.jl` with the same scope as `bin/repl`, so that controllers and other components can be tested right away. By these means, this PR fixes #281.

The result is that you can type `] test` in an REPL to start the `test/runtests.jl` routine, just as you would with a Julia package. It works likewise with a `bin/repl` session and with a plain `julia` REPL.

As an additional bug fix, SearchLight.jl is added to the dependencies if `dbsupport=true` is specified, which resolves a large stack of warnings previously shown.

Note that the approach taken here is slightly different from the one I proposed in #281. Namely, there is no additional `test/Project.toml`, instead all dependencies are specified in the base `Project.toml`. The original approach did not work in the same Julia session that generates the other files; making it work would have needed the `bin/repl` to be called, which would have slowed down the app generation unnecessarily.

### CODE REVIEW

**Comment by essenciary** [comment]
@mirkobunse Thanks so much for this contribution! Can you please detail why we can't have `test/Project.toml`? It's the Julia best practice and it's a shame to implement a solution that goes against the best practices. More importantly, it has the important downside of adding testing dependencies to the app (and there can be quite a few packages used just for testing). I would like to see if we can find a solution to use `test/Project.toml`.

**Comment by mirkobunse** [comment]
Sure! First of all, I agree that going against Julia best practices is not desireable and having test dependencies in a separate `test/Project.toml` would be desireable.

The problem actually lies in `src/AppName.jl` and how `bootstrap.jl` uses it:

- First, `boostrap.jl` says `include("src/AppName.jl")` instead of `using AppName`. This is against best practices because it effectively circumvents Julias dependency checks for the AppName module. If I replace that line with a `using` statement, it will crash because `Logging` (which is used in AppName) is not an explicit dependency of AppName.
- Second, the default `src/AppName.jl` does not only define a `main()` method, but also calls that method straight away. Instead, the method should be called whereever it is used, e.g in `bootstrap.jl`. Typing `using AppName` anywhere should only bring the exported methods into scope but not call them.

Both issues should be fixed, but that's a separate concern I did not want to make in this unit-testing-related PR.

Finally, including `bootstrap.jl` in `test/runtests.jl` activates the base `Project.toml` anyways, so that the separate `test/Project.toml` would not have been active during the tests. That's of course easy to fix, instead of `include("../bootstrap.jl")` i just had to include `include("../src/AppName.jl")`, which is equivalent to what the bootstrap does but without the activation of the base project. However, since Julia's dependency checks are broken this way, as explained above, the user will be stuck with a mean side effect: whenever he adds a dependency to the base project, he must explicitly also add it to the test project. If the dependency check were not broken, Julia would take care of that.

My suggestion is to keep the PR as it is and fix the issues above in a separate PR. Alternatively, we can stall this one until the issues above are fixed and merge their fixes here, later.

**Comment by mirkobunse** [comment]
Alternatively, I can add the separate `test/Project.toml`; I already have prepared a commit for that. Advantage: no test dependencies in the base project. Disadvantage: user might need to add additional dependencies twice, once in the base project and once in the test project.

**Comment by essenciary** [comment]
> First, boostrap.jl says include("src/AppName.jl") instead of using AppName. This is against best practices because it effectively circumvents Julias dependency checks for the AppName module. If I replace that line with a using statement, it will crash because Logging (which is used in AppName) is not an explicit dependency of AppName.

Oh, I was not aware of that, we need to add `Logging` for sure. 

---

> Second, the default src/AppName.jl does not only define a main() method, but also calls that method straight away. Instead, the method should be called whereever it is used, e.g in bootstrap.jl. Typing using AppName anywhere should only bring the exported methods into scope but not call them.

Makes sense. As long as it's a non-breaking change we can add it. 

---

1. Why can't `runtest.jl` include the relevant parts from `bootstrap.jl`? 
2. Don't understand why the test Project.toml would include the deps from the app (maybe I just need to run the code). The test Project.toml has the app as dependency plus the dedicated test dependencies. 

---

If the missed dependency on `Logging` is the problem, it's literally one line to fix in the generator and we can change `bootstrap.jl` as you suggested. If then we can just pack a separate `Project.toml` for test, that's great. I'm reluctant to merge as is due to this adding the test dependencies into the app's Project.toml file which can be an issue for users. 

---

Moving on to a related topic: test dependencies. I've done some research into this a while ago (asked the community) and two best practices came up: using `SafeTestsets` and `TestSetExtensions`. Should we set these up as a best practice, add a boilerplate test example and nudge the users towards these as the Genie best practice?

**Comment by mirkobunse** [comment]
> Oh, I was not aware of that, we need to add Logging for sure.

> Makes sense. As long as it's a non-breaking change we can add it.

Should I make these two changes directly in this PR, or should we keep things separate? Since you agree to have these changes, I'd be available to add them to this PR.

> 1. Why can't runtest.jl include the relevant parts from bootstrap.jl?
> 2. Don't understand why the test Project.toml would include the deps from the app (maybe I just need to run the code). The test Project.toml has the app as dependency plus the dedicated test dependencies.

With the changes discussed above, these two points are no problem. `runtest.jl` could include the `bootstrap.jl` and `test/Project.toml` would not need to include the app dependencies.

> Should we set these up as a best practice, add a boilerplate test example and nudge the users towards these as the Genie best practice?

I'd prefer to not be forced to use particular test packages, as the standard testing suite of Julia is already pretty powerful. Right now, Genie only forces users to stick to conventions about how concerns are separated (MVC and file structure), which makes perfect sense for a MVC-based framework. Forcing users to stick to particular testing practices, in contrast, goes beyond that. In fact, it would feel a little arbitrary to me.

**Comment by essenciary** [comment]
> Should I make these two changes directly in this PR, or should we keep things separate? Since you agree to have these changes, I'd be available to add them to this PR.

That'd be awesome, thank you. I think same, they are related and it's simpler, the PR is still manageable in terms of changes. 

> I'd prefer to not be forced to use particular test packages. 

Agreed.

**Comment by mirkobunse** [comment]
Cool, thanks for your feedback!

I made the changes, but a few things broke. Namely, the following lines appeared in the logs of the Genie unit tests (all other outputs of the unit test remained the same):

```
WARNING: redefinition of constant config. This may fail, cause incorrect answers, or produce other errors.

ERROR: cannot declare SECRET_TOKEN constant; it already has a value
top-level scope at /tmp/jl_PzNtFF/fullstack_test/config/secrets.jl:1
in expression starting at /tmp/jl_PzNtFF/fullstack_test/config/secrets.jl:1

ERROR: cannot declare ASSET_FINGERPRINT constant; it already has a value
top-level scope at /tmp/jl_PzNtFF/fullstack_test/config/initializers/assets_fingerprint.jl:1
in expression starting at /tmp/jl_PzNtFF/fullstack_test/config/initializers/assets_fingerprint.jl:1
```

I have tried to remove the definitions of `SECRET_TOKEN` and `ASSET_FINGERPRINT` in the Genie source code, so that `config/secrets.jl` and `config/initializers/assets_fingerprint.jl` can set the constants without a warning. However, I fear these changes might break something that is not covered by the unit tests.

These warnings might come from some of the appearances of `Core.eval(Genie, ..)`, of `Core.eval(@__MODULE__, ..)`, of  `Core.eval(context, ..)`, and `Base.eval(Main, ..)`. In fact, evaluating code in other modules/contexts is breaking the separation of concerns that modules achieve and module authors assume. I'd be ideal to get rid of all `eval` statements.

I also suggest to move all global state, like `SECRET_TOKEN`, `ASSET_FINGERPRINT`, and `config`, to some central place, like a single dict/struct which Genie and the App can access, instead of distributing the global state across all the code.

**Comment by essenciary** [comment]
Thank you for the updates! Yes, we don't have any tests explicitly covering those features. I would like to get rid of the evals if straightforward and non-breaking. I'll check. 

I'll merge the PR into a new branch to pick it up from here - thank you for the contributions! 

Quick question: is the removal of `genie.jl` and the addition of the code in `Genie.jl` backwards compatible with the existing apps?

**Comment by mirkobunse** [comment]
Alright!

> Quick question: is the removal of genie.jl and the addition of the code in Genie.jl backwards compatible with the existing apps?

Due to the warnings, I do not expect the current state of this PR to be backwards compatible. This expectation comes from the eval statements, not from `genie.jl` though.

As for `genie.jl` specifically, I think I only missed one detail which can be fixed easily. In the following line, the file `genie.jl` would have evaluated `@__MODULE__` to be AppName (or whatever you named your App, due to the inclusion of the genie file from that module). In `Genie.genie()`, however, it evaluates to `Genie` instead. The obvious fix is to change the new function to `Genie.genie(context)` (without a default value for the argument) and pass the new parameter to `load`.

```
load(context = @__MODULE__)
```

**Comment by essenciary** [comment]
@mirkobunse Thanks, I'll add that in! 

However, I run into a different issue - seems that the `runtests.jl` file is mising: 

```julia
julia> Genie.newapp("moo")
ERROR: SystemError: opening file "C:\\Users\\adria\\moo\\test\\runtests.jl": No such file or directory
Stacktrace:
 [1] systemerror(::String, ::Int32; extrainfo::Nothing) at .\error.jl:168
 [2] #systemerror#48 at .\error.jl:167 [inlined]
 [3] systemerror at .\error.jl:167 [inlined]
 [4] open(::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Bool, append::Nothing) at .\iostream.jl:284
 [5] open(::String, ::String; lock::Bool) at .\iostream.jl:346
 [6] open(::String, ::String) at .\iostream.jl:346
 [7] open(::Genie.Generator.var"#23#26"{Tuple{String,String}}, ::String, ::Vararg{String,N} where N; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at .\io.jl:323
 [8] open at .\io.jl:323 [inlined]
 [9] write_app_custom_files(::String, ::String) at C:\Users\adria\.julia\dev\Genie\src\Generator.jl:335
 [10] scaffold(::String, ::String) at C:\Users\adria\.julia\dev\Genie\src\Generator.jl:262
 [11] microstack_app(::String, ::String) at C:\Users\adria\.julia\dev\Genie\src\Generator.jl:282
 [12] newapp(::String; autostart::Bool, fullstack::Bool, dbsupport::Bool, mvcsupport::Bool, testmode::Bool) at C:\Users\adria\.julia\dev\Genie\src\Generator.jl:492
 [13] newapp(::String) at C:\Users\adria\.julia\dev\Genie\src\Generator.jl:489
 [14] top-level scope at REPL[3]:1
```

**Comment by essenciary** [comment]
Ah, I think it's because we need to create the `test/` folder first.

**Comment by essenciary** [comment]
@mirkobunse Trying to understand your intentions with the code here please. I created a new app and in `test/Project.toml` we have

```julia
[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
```

and `runtest.jl` has: 

```julia
using Moo, Test

# implement your tests here
@test 1 == 1
```

I don't think we need all the deps do we? We just need `Test`?

**Comment by mirkobunse** [comment]
Sure, just keep asking whenever something's unclear!

> Ah, I think it's because we need to create the test/ folder first.

Good you point this problem out! I can only test on Linux, where the `test/` folder just appeared and no error was raised.

> I don't think we need all the deps do we? We just need Test?

These are all the original deps of the `Project.toml`, plus `Test`. Calling `] test` complained when any of these were missing.

**Comment by essenciary** [comment]
@mirkobunse Now this works 100%! 🎉 
Genie is still backwards compatible with all the apps generated so far although obviously the apps will be generated differently from now on. 

The only major change moving on (and that I'm split about) is the fact that windows scripts from `bin/` will now have to be run from the root of the app (whether before they were meant to be run from within `bin/`. The reason was that windows users are less terminal savvy and I thought they will want to double click the bat script directly to start the Genie session. However, with the removal of the `cd` call from `bootstrap.jl` we now need to assume that all apps are run within the root of the app otherwise paths can't be resolved (eg the secrets error was caused by this). 

In a sense, the fact that *nix apps were started from the root of the app and windows from within `bin/` always bothered me - but I'm not sure how well this now serves windows users. To address this problem I think the best next step is to have a `genie` binary added to the PATH which can generate and load apps independently. 

I will tag a new version with these features and then move on to the `SECRET_TOKEN` + `Ref` PR, thanks so much, that sounds like a great approach!

**Comment by mirkobunse** [comment]
Cool, thanks for digging into it!

> windows scripts from `bin/` will now have to be run from the root of the app

You can change this behaviour by changing the `project=@.` in the scripts to `project=..`, I guess. On Linux, the `@.` allows to call the script from both the base directory and the `bin/` directory (in contrast to `project=.`, which would only allow the script to be called from the base directory).

Can you check the terminal output of `julia --help` on Windows? Maybe there's a different value for `project`, which achieves the Linux behaviour on Windows.

Yet another idea is to combine the current bootstrap file with `julia -e`, to evaluate another line of code before the bootstrap file is called.

```
julia <all other arguments, but without project=@.> -e 'cd(".."); using Pkg; Pkg.activate(".")'
```

**Pull request merged**
