### PR TITLE
Update 4-1--Developing_MVC_Web_Apps.md

### PR DESCRIPTION
**Pull request by jglee1**
"using WatchTonight.Movies" did not work.

"using Movies" worked for me.

### CODE REVIEW

**Comment by essenciary** [comment]
Most likely because you're using Genie 4. What version of Genie are you using?

**Comment by jglee1** [comment]
It's Genie v5.3.2.

**Comment by jglee1** [comment]
(WatchTonight) pkg> st
     Project WatchTonight v0.1.0
      Status `C:\Users\JG1\Documents\vim\genie\MyProject9\WatchTonight\Project.toml`
  [336ed68f] CSV v0.10.4
  [c43c736e] Genie v5.4.1
  [6d011eab] Inflector v1.0.1
  [340e8cb6] SearchLight v2.7.1
  [21a827c4] SearchLightSQLite v2.2.0
  [ade2ca70] Dates
  [56ddb016] Logging

**Comment by essenciary** [comment]
@jglee1 then it's very strange - it should definitely work on Genie v5. Can you please share the app?

**Pull request closed without merging**
