### PR TITLE
Websockets fix

### PR DESCRIPTION
**Pull request by jochenkrattenmacher**
Makes the websockets connection more robust
#613

### CODE REVIEW

**Comment by AbhimanyuAryan** [comment]
tested on phone it's definitely stable

**Comment by essenciary** [comment]
@jochenkrattenmacher @AbhimanyuAryan is this good to merge?

**Comment by AbhimanyuAryan** [comment]
@essenciary tested on GenieBuilder, Stipple, GenieFramework looks great but don't merge it yet. Will need refactoring based on what we discussed in OSS

**Comment by jochenkrattenmacher** [comment]
it seems to work for me, can't say much more ;) . I can just say that the numbers which are in there, i.e.
const maxNumberOfAttempts = 10;
const intervalTime = 500;

and "trial < 4" 

have been chosen rather arbitrarily. And probably one could rename "trial" to "currentAttempt" to make the whole thing more consistent...

Perhaps slightly more seriously,  "subscribe();" in the close handler probably is redundant (since subscribe is already in the open handler). But I didn't test thoroughly whether one can really omit it (logically one would think this should be the case), and this redundancy doesn't seem to have adverse effects. I'll leave that to you guys

**Comment by essenciary** [comment]
@jochenkrattenmacher Thanks for the PR, it looks great! Exactly, Abhi and I were talking about the numbers and would like to expose them as user configurable values from within Genie.

**Comment by jochenkrattenmacher** [comment]
I just added two small changes to simplify bugfixing... 

While I am at it, I just want to point out that currently, app_ready() from Stipple is called upon every subscription. That means that a new keepalive interval is created upon every (re-)subscription (unnecessarily). Not a big issue, but probably good to be aware of. Cheers

**Comment by AbhimanyuAryan** [comment]
> yep I think that'd be great :)
> 
> I just added two small changes to simplify bugfixing...
> 
> While I am at it, I just want to point out that currently, app_ready() from Stipple is called upon every subscription. That means that a new keepalive interval is created upon every (re-)subscription (unnecessarily). Not a big issue, but probably good to be aware of. Cheers

thanks

**Comment by jochenkrattenmacher** [comment]
Thanks for the merge! Just a small note 👀 : This can be removed: `if (trial == 4)`. Or the 4 should be replaced by Genie.Settings.webchannels_subscription_trails

**Comment by AbhimanyuAryan** [comment]
thanks @jochenkrattenmacher yes I missed that magic number. I'll push it

**Comment by jochenkrattenmacher** [comment]
Another note 👀 : 

In Configuration.jl, the setting currently is named `webchannels_subscription_trails`

it should be `webchannels_connection_attempts` however in order to make sense to channel.js, which refers to 
`Genie.Settings.webchannels_connection_attempts `

**Comment by jochenkrattenmacher** [comment]
bumping this since it is actually quite important... Without correctly naming the setting, this whole thing doesn't work at all :x.

> Another note 👀 :
> 
> In Configuration.jl, the setting currently is named `webchannels_subscription_trails`
> 
> however, it should be named `webchannels_connection_attempts` in order to make sense to channel.js, which refers to `Genie.Settings.webchannels_connection_attempts `.
> 
> I also would probably increase the default value to 6 or so at least (I need a few attempts usually when loading my SPA, which is quite big)

**Comment by AbhimanyuAryan** [comment]
Let me check

**Comment by AbhimanyuAryan** [comment]
actually `webchannels_connection_wait_attempts` should be renamed to `webchannels_connection_attempts` it's accessed in `maxAttempts`. `webchannels_subscription_trails` is fine. It's `4` by default and compared against trail

**Comment by jochenkrattenmacher** [comment]
oh yep, true that!

**Comment by AbhimanyuAryan** [comment]
@jochenkrattenmacher also you can change trail value from 4 to 6 in `.env` file. This is why we added it in Configurations :)

**Pull request merged**
