### PR TITLE
Replace identical comparison operators with functions

### PR DESCRIPTION
**Pull request by Hieronimo**

### CODE REVIEW

**Comment by essenciary** [comment]
@Hieronimo Can you please explain what's the benefit of this?

**Comment by hhaensel** [comment]
I'm a bit divided on this PR. There are some discussions that the compiler is not able to optimise isnothing in some situations, e.g.
https://stackoverflow.com/questions/56852880/comparing-julia-variable-to-nothing-using-or
and 
https://github.com/JuliaLang/julia/issues/27681

I think that for the cases here it is rather irrelevant, because it is not performance critical.

**Comment by Hieronimo** [comment]
It compares types and works with multiple dispatch:
```julia
isnothing(::Any) = false
isnothing(::Nothing) = true
```
It's faster than `==` but slower than `===`:
```julia
julia> n = 5.0
5.0

julia> @btime isnothing(n)
  15.380 ns (0 allocations: 0 bytes)
false

julia> @btime n == nothing
  19.777 ns (0 allocations: 0 bytes)
false

julia> @btime n === nothing
  1.587 ns (0 allocations: 0 bytes)
false

```
```julia
julia> a = nothing

julia> @btime isnothing(a)
  3.158 ns (0 allocations: 0 bytes)
true

julia> @btime a == nothing
  19.774 ns (0 allocations: 0 bytes)
true

julia> @btime a === nothing
  1.587 ns (0 allocations: 0 bytes)
true

```
There is no performance improvement, just more flexibility.

**Comment by hhaensel** [comment]
Your timings suffer from the fact that they all run at the REPL. In order to have reliable timings it is recommended to run the timing on functions. I did the following:
```
julia> f1(x) = isnothing.(x)
f1 (generic function with 1 method)

julia> f2(x) = x .=== nothing
f2 (generic function with 1 method)

julia> f3(x) = x .== nothing
f3 (generic function with 1 method)

julia> t = [x<0.5 ? nothing : rand() for x in rand(10000)];

julia> findall(isnothing, t) |> length
4899

julia> @btime f1(t); @btime f2(t); @btime f3(t);
  2.111 μs (3 allocations: 5.55 KiB)
  2.211 μs (3 allocations: 5.55 KiB)
  2.111 μs (3 allocations: 5.55 KiB)
```
Multiple runs show, there is no clear favourite and all routines perform the same in my example.
So it all is a question of taste ...

**Comment by essenciary** [comment]
@Hieronimo sorry for all the work you put but there doesn't seem to be a clear benefit for merging this. We're very happy with contributions and quite grateful for the support - so my suggestion for the future is, if it's not a clear bug fix or feature or benefit, check with us first if the contribution makes sense, before putting in all the work.

**Pull request closed without merging**
